name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # İş akışı her gün gece yarısı çalışır
  push:
    branches:
      - main  # Ana branşa her push işlemi yapıldığında çalışır
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Activity Log Script
        run: |
          npm install
          npm run update-readme

      - name: Fetch recent contributions
        run: |
          recent_contributions=$(jq -r 'map("<li><a href=\"\\(.repo.url)\">\\(.repo.name)</a>: \\(.payload.commits | map(.message) | join(", "))</li>") | join("\n")' contributions.json)
          sed -i 's|<div align="center">.*</div>|<div align="center">\n'"$recent_contributions"'\n</div>|g' README.md

      - name: Check for changes
        id: git_status
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          echo "::set-output name=changes::$(git status --porcelain)"

      - name: Commit and Push changes
        if: steps.git_status.outputs.changes != ''
        run: |
          git commit -m "Updated README with recent activity"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
