name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow every day at midnight.
  push:
    branches:
      - main  # This runs the workflow on every push to the main branch.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          sed -i 's|<div align="center">.*</div>|<div align="center">\n  <img src="https://github-readme-stats.vercel.app/api?hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=vue-dark&locale=en&hide_border=false&username=gumaruw" height="150" alt="stats graph"  />\n  <img src="https://github-readme-stats.vercel.app/api/top-langs?locale=en&hide_title=false&layout=compact&card_width=320&langs_count=5&theme=vue-dark&hide_border=false&username=gumaruw" height="150" alt="languages graph"  />\n</div>|g' README.md

      - name: Check for changes
        id: git_status
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          echo "::set-output name=changes::$(git status --porcelain)"

      - name: Commit changes
        if: steps.git_status.outputs.changes != ''
        run: |
          git commit -m "Update README"
          git push
